package tugas;

import File.koneksi;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import tugas.form_sewa;
import koneksi.konek;

public class form_sewa extends javax.swing.JFrame {
    
    public String datachooser, datachooser1;
    public String Ktp, Nama, Tlp;
    public String no, Tipe, Tarif, cekin, cekout, lama, total;
    String tglMasuk, tglKeluar;
    private int tglM, blnM, thnM, tglK, beli, harga, ttl;
    private Date tglPinjam;
    private Date tglHrsKmbl;
    private Date tglkmbl;
    private String tglHrsKembali;
    private String tglKembali;
    private int iBulan;
    private String sBulan;
    private String kBulan;
    private int inBulan;
    private Connection con= new konek().Connect();
    private DefaultTableModel tabmode;
    Object[] Baris= {"No_Kamar","Tipe_Kamar","Tarif","Fasilitas","Status"};
    private Object JasperfillManager;
    
    public form_sewa() {
        initComponents();
        kosong();
        aktif();
        autonumber();
        atur();
        datatable();
    }

    protected void aktif(){
        txt_lama.requestFocus();
        tabmode= new DefaultTableModel(null, Baris);
        tabel.setModel(tabmode);
    }
    
    protected void kosong(){
    txt_ktp.setText("");
    txt_nama.setText("");
    txt_tlp.setText("");
    txt_no.setText("");
    txt_tipe.setText("");
    txt_tarif.setText("");
    tgl_cekin.setDate(null);
    tgl_cekout.setDate(null);
    txt_lama.setText("");
    txt_total.setText("");
    }
    
    private void autonumber(){
        String Id_Sewa="";
        try{
            String sql= "SELECT Id_Sewa FROM tbl_sewa order by id_Sewa asc";
            PreparedStatement stt= con.prepareStatement(sql);
            ResultSet res= stt.executeQuery(sql);
            
            while(res.next()){
                Id_Sewa= res.getString("Id_Sewa");
            }
            }catch(SQLException sqle){Id_Sewa="";}
        
        if(Id_Sewa.length()<1){Id_Sewa="Is0000";}
        String ur= Id_Sewa.substring(2);
        int u= Integer.parseInt(ur)+1;
        System.out.println(ur+"=="+u);
            if(u<10)
            {ur="000"+u;}
            else if(u<100)
            {ur="00"+u;}
            else if(u<1000)
            {ur="0"+u;}
            else
            {ur=""+u;}
        Id_Sewa= "Is"+ur;
        txt_id.setText(Id_Sewa);
    }
    
    public void itemTerpilih(){
        Form_popupPelanggan Pp= new Form_popupPelanggan();
        Pp.plgn= this;
        txt_ktp.setText(Ktp);
        txt_nama.setText(Nama);
        txt_tlp.setText(Tlp);
    }
    
    public void terpilihKamar(){
        Form_popupKamar Pp= new Form_popupKamar();
        Pp.kmr= this;
        txt_no.setText(no);
        txt_tipe.setText(Tipe);
        txt_tarif.setText(Tarif);
        txt_tarif.requestFocus();
    }
    
    protected void atur(){
        txt_id.setEnabled(false);
        txt_ktp.setEnabled(false);
        txt_nama.setEnabled(false);
        txt_tlp.setEnabled(false);
        txt_no.setEnabled(false);
        txt_tipe.setEnabled(false);
        txt_tarif.setEnabled(false);
        tgl_cekin.setEnabled(true);
        tgl_cekout.setEnabled(true);
        txt_lama.setEnabled(true);
        txt_total.setEnabled(true);
    }
    
     protected void datatable(){
        Object[]Baris={"Id_Sewa","Nama","Telpon","No_Kamar","Tipe_Kamar","Tarif","Cek_In","Cek_Out","Lama_Hari","Total_Harga"};
        tabmode= new DefaultTableModel(null, Baris);
        String cari = txt_cari.getText();
        
        try{
            String sql ="Select * from tbl_sewa where No_kamar like '%"+cari+"%' or Nama like '%"+cari+"%' order by No_Kamar";
            Statement stt= con.createStatement();
            ResultSet hasil= stt.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7),
                hasil.getString(8),
                hasil.getString(9),
                hasil.getString(10)
            });
            }
                tabel.setModel(tabmode);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dipanggil" +e);
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_ktp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tlp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_tarif = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tgl_cekin = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        tgl_cekout = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txt_lama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_tipe = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\bill.png")); // NOI18N
        jLabel1.setText(" Data Sewa Kamar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 13, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1350, 60));

        btn_kembali.setBackground(new java.awt.Color(255, 255, 255));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_kembali.setIcon(new javax.swing.ImageIcon("D:\\knobs\\PNG\\Knob Left.png")); // NOI18N
        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel5.setBackground(new java.awt.Color(255, 0, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Data"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ktp.setBackground(new java.awt.Color(255, 0, 102));
        txt_ktp.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_ktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ktpActionPerformed(evt);
            }
        });
        jPanel3.add(txt_ktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 131, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Search\\Search_16x16.png")); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("No. KTP");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 75, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nama");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 115, -1, -1));

        txt_nama.setBackground(new java.awt.Color(255, 0, 102));
        txt_nama.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 155, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("No. Telpon");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txt_tlp.setBackground(new java.awt.Color(255, 0, 102));
        txt_tlp.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_tlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tlpActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 155, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("No. Kamar");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_no.setBackground(new java.awt.Color(255, 0, 102));
        txt_no.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Tipe Kamar");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Tarif");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txt_tarif.setBackground(new java.awt.Color(255, 0, 102));
        txt_tarif.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_tarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tarifActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 157, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Cek In");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        tgl_cekin.setBackground(new java.awt.Color(255, 0, 102));
        tgl_cekin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_cekinPropertyChange(evt);
            }
        });
        jPanel3.add(tgl_cekin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 130, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Cek Out");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        tgl_cekout.setBackground(new java.awt.Color(255, 0, 102));
        tgl_cekout.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_cekoutPropertyChange(evt);
            }
        });
        jPanel3.add(tgl_cekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 130, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Total");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        txt_total.setBackground(new java.awt.Color(255, 0, 102));
        txt_total.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 161, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Refresh\\Refresh_24x24.png")); // NOI18N
        jButton3.setText("Bersih");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        tambah.setBackground(new java.awt.Color(255, 255, 255));
        tambah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tambah.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Save\\Save_24x24.png")); // NOI18N
        tambah.setText("Simpan");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel3.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        txt_id.setBackground(new java.awt.Color(255, 0, 102));
        txt_id.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 129, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Id Sewa");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 34, -1, 20));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Search\\Search_16x16.png")); // NOI18N
        jButton7.setText("Cari");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 30));

        txt_lama.setBackground(new java.awt.Color(255, 0, 102));
        txt_lama.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_lama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lamaActionPerformed(evt);
            }
        });
        txt_lama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lamaKeyTyped(evt);
            }
        });
        jPanel3.add(txt_lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 160, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Lama Hari");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        txt_tipe.setBackground(new java.awt.Color(255, 0, 102));
        txt_tipe.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_tipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipeActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 160, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Refresh\\Refresh_16x16.png")); // NOI18N
        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, 540));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, 570));

        jPanel6.setBackground(new java.awt.Color(255, 0, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Sewa Kamar"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setBackground(new java.awt.Color(255, 0, 102));
        tabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 920, 450));

        txt_cari.setBackground(new java.awt.Color(255, 0, 102));
        txt_cari.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });
        jPanel4.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Search\\Search_16x16.png")); // NOI18N
        jButton6.setText("Cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Delete\\Delete_24x24.png")); // NOI18N
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 540));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 960, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ktpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ktpActionPerformed

    private void txt_tarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tarifActionPerformed

    private void txt_tlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tlpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Form_popupPelanggan Pp= new Form_popupPelanggan();
        Pp.plgn= this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_tipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipeActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Form_popupKamar Pp= new Form_popupKamar();
        Pp.kmr= this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tbl_sewa values (?,?,?,?,?,?,?,?,?,?)";
        try{
           PreparedStatement stt = con.prepareStatement(sql);
           stt.setString(1, txt_id.getText());
           stt.setString(2, txt_nama.getText());
           stt.setString(3, txt_tlp.getText());
           stt.setString(4, txt_no.getText());
           stt.setString(5, txt_tipe.getText());
           stt.setString(6, txt_tarif.getText());
           stt.setString(7, datachooser);
           stt.setString(8, datachooser1);
           stt.setString(9, txt_lama.getText());
           stt.setString(10, txt_total.getText());
           
           stt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            txt_id.requestFocus();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+ e);
        }
        datatable();
        autonumber();
        
    }//GEN-LAST:event_tambahActionPerformed

    private void tgl_cekinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_cekinPropertyChange
        // TODO add your handling code here:
        if(tgl_cekin.getDate() !=null){
        SimpleDateFormat Format= new SimpleDateFormat("dd MMM yyyy");
        datachooser= Format.format(tgl_cekin.getDate());
        }
    }//GEN-LAST:event_tgl_cekinPropertyChange

    private void tgl_cekoutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_cekoutPropertyChange
        // TODO add your handling code here:
        if(tgl_cekout.getDate() !=null){
        SimpleDateFormat Format= new SimpleDateFormat("dd MMM yyyy");
        datachooser1= Format.format(tgl_cekout.getDate());
        }
    }//GEN-LAST:event_tgl_cekoutPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
int tahunH = Integer.parseInt(datachooser.substring(7, 11));
int hariH = Integer.parseInt(datachooser.substring(0, 2));
sBulan = (String) datachooser.substring(3, 6);
if (sBulan.compareTo("Jan") == 0) {
iBulan = 1;
} else if (sBulan.compareTo("Feb") == 0) {
iBulan = 2;
} else if (sBulan.compareTo("Mar") == 0) {
iBulan = 3;
} else if (sBulan.compareTo("Apr") == 0) {
iBulan = 4;
} else if (sBulan.compareTo("May") == 0) {
iBulan = 5;
} else if (sBulan.compareTo("Jun") == 0) {
iBulan = 6;
} else if (sBulan.compareTo("Jul") == 0) {
iBulan = 7;
} else if (sBulan.compareTo("Aug") == 0) {
iBulan = 8;
} else if (sBulan.compareTo("Sep") == 0) {
iBulan = 9;
} else if (sBulan.compareTo("Oct") == 0) {
iBulan = 10;
} else if (sBulan.compareTo("Nov") == 0) {
iBulan = 11;
} else {
iBulan = 12;
}
int tahunK = Integer.parseInt(datachooser1.substring(7, 11));
int hariK = Integer.parseInt(datachooser1.substring(0, 2));
kBulan = (String) datachooser1.substring(3, 6);
if (kBulan.compareTo("Jan") == 0) {
inBulan = 1;
} else if (kBulan.compareTo("Feb") == 0) {
inBulan = 2;
} else if (kBulan.compareTo("Mar") == 0) {
inBulan = 3;
} else if (kBulan.compareTo("Apr") == 0) {
inBulan = 4;
} else if (kBulan.compareTo("May") == 0) {
inBulan = 5;
} else if (kBulan.compareTo("Jun") == 0) {
inBulan = 6;
} else if (kBulan.compareTo("Jul") == 0) {
inBulan = 7;
} else if (kBulan.compareTo("Aug") == 0) {
inBulan = 8;
} else if (kBulan.compareTo("Sep") == 0) {
inBulan = 9;
} else if (kBulan.compareTo("Oct") == 0) {
inBulan = 10;
} else if (kBulan.compareTo("Nov") == 0) {
inBulan = 11;
} else {
inBulan = 12;
}
int hasilHari = hariK - hariH;
int hasilBulan = (inBulan - iBulan) * 30;
int hasiltahun = (tahunK - tahunH) * 365;
int totalhari = (hasilHari + hasilBulan + hasiltahun);
txt_lama.setText(String.valueOf(totalhari));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_lamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lamaActionPerformed
        // TODO add your handling code here:
        beli= Integer.parseInt(txt_lama.getText());
        harga= Integer.parseInt(txt_tarif.getText());
        ttl= beli*harga;
        txt_total.setText(String.valueOf(ttl));                                       

    }//GEN-LAST:event_txt_lamaActionPerformed

    private void txt_lamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lamaKeyReleased
        // TODO add your handling code here:
        int x, y, z;
        x= Integer.valueOf(txt_lama.getText());
        y= Integer.valueOf(txt_tarif.getText());
        z= x*y;
        txt_total.setText("" +z);
    }//GEN-LAST:event_txt_lamaKeyReleased

    private void txt_lamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lamaKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int ok = JOptionPane.showConfirmDialog(null, "Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
        if(ok==0){
        String sql = "Delete from tbl_sewa where Id_Sewa = '"+txt_id.getText()+"'";
        try{
            PreparedStatement stt = con.prepareStatement(sql);
            stt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
            kosong();
            txt_id.requestFocus();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus");
        }
        datatable();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
         int bar = tabel.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        
        
        txt_id.setText(a);
        txt_nama.setText(b);
        txt_tlp.setText(c);
        txt_no.setText(d);
        txt_tipe.setText(e);
        txt_tarif.setText(f);
        if(tgl_cekin.equals(g)){
        SimpleDateFormat Format= new SimpleDateFormat("dd MMM yyyy");
        datachooser= Format.format(tgl_cekin.getDate());
        }
        if(tgl_cekout.equals(h)){
        SimpleDateFormat Format= new SimpleDateFormat("dd MMM yyyy");
        datachooser1= Format.format(tgl_cekout.getDate());
        }
        txt_lama.setText(i);
        txt_total.setText(j);
        atur();
    }//GEN-LAST:event_tabelMouseClicked

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed

        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_txt_cariKeyPressed

    private void jButton1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AncestorAdded
//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_sewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tgl_cekin;
    private com.toedter.calendar.JDateChooser tgl_cekout;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_ktp;
    private javax.swing.JTextField txt_lama;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_tarif;
    private javax.swing.JTextField txt_tipe;
    private javax.swing.JTextField txt_tlp;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

}
