package tugas;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.*;
import koneksi.konek;

public class Form_Kamar extends javax.swing.JFrame {

    public String tanggal;
    private Connection con = new konek().Connect();
    private DefaultTableModel tabmode;
    
    public Form_Kamar() {
        initComponents();
        aktif();
        kosong();
       // atur();
        //autonumber();
        datatable();
       // datatable1();
    }
    
    private void aktif(){
        txt_kmr.requestFocus();
    }
    
    protected void kosong(){
        txt_kmr.setText("");
        cb_tipe.setSelectedItem("--Pilih Kamar--");
        txt_tarif.setText("");
        txt_status.setText("");
        txt_fasilitas.setText("");
        txt_cari.setText("");
    }
    
   /* protected void atur(){
        txt_kmr.setEnabled(false);
        cb_tipe.setEnabled(true);
        txt_tarif.setEnabled(false);
        txt_fasilitas.setEnabled(false);
        txt_status.setEnabled(true);
    }*/
   /* private void autonumber(){
        String id_kamar="";
        try{
            String sql= "SELECT id_kamar FROM id order by id_kamar asc";
            PreparedStatement stt= con.prepareStatement(sql);
            ResultSet res= stt.executeQuery(sql);
            
            while(res.next()){
                id_kamar= res.getString("id_kamar");
            }
            }catch(SQLException sqle){id_kamar="";}
        if(id_kamar.length()<1){id_kamar="Km0000";}
        String ur= id_kamar.substring(2);
        int u= Integer.parseInt(ur)+1;
        System.out.println(ur+"=="+u);
            if(u<10)
            {ur="000"+u;}
            else if(u<100)
            {ur="00"+u;}
            else if(u<1000)
            {ur="0"+u;}
            else
            {ur=""+u;}
        id_kamar= "Km"+ur;
        txt_id.setText(id_kamar);
        
    }*/
    
    protected void datatable(){
        Object[]Baris={"No_Kamar","Tipe_Kamar","Tarif","Fasilitas","Status"};
        tabmode= new DefaultTableModel(null, Baris);
        String cari = txt_cari.getText();
        
        try{
            String sql ="Select * from tbl_kamar where No_Kamar like '%"+cari+"%' or Status like '%"+cari+"%' order by No_Kamar";
            Statement stt= con.createStatement();
            ResultSet hasil= stt.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5)
            });
            }
                tabel.setModel(tabmode);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Dipanggil" +e);
            
            
        }
    }
    
    /* protected void datatable1(){
        Object[]Baris={"No_KTP","Nama","Jenis_Kelamin","Alamat","Telpon","No_Kamar","Tipe_Kamar","Tanggal_Masuk"};
        String cari= txt_carik.getText();
    
    try{
            String sql = "SELECT * FROM tbl_pelanggan where No_KTP like'%"+cari+"%' or Nama like '%"+cari+"%' order by No_KTP";
            Statement stt = con.createStatement();
            ResultSet res = stt.executeQuery(sql);
            while (res.next()){              
                txt_nama.setText(res.getString("Nama"));
            } 
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Di Panggil"+ e);
        }
    }*/
    
    // public JDateChooser(){
         
   //  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_kmr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_tipe = new javax.swing.JComboBox();
        txt_status = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tarif = new javax.swing.JTextField();
        btn_ubah = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_fasilitas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btn_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        btn_kembali = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data Kamar"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("No. Kamar");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_kmr.setBackground(new java.awt.Color(255, 0, 102));
        txt_kmr.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_kmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 180, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Tipe Kamar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cb_tipe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cb_tipe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Kamar--", "Standar", "Bisnis", "VIP", "VVIP" }));
        cb_tipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipeActionPerformed(evt);
            }
        });
        jPanel3.add(cb_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 180, -1));

        txt_status.setBackground(new java.awt.Color(255, 0, 102));
        txt_status.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 180, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Tarif Per Malam");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_tarif.setBackground(new java.awt.Color(255, 0, 102));
        txt_tarif.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_tarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tarifActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, -1));

        btn_ubah.setBackground(new java.awt.Color(255, 255, 255));
        btn_ubah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_ubah.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Upload\\Upload_24x24.png")); // NOI18N
        btn_ubah.setText(" Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 100, -1));

        btn_bersih.setBackground(new java.awt.Color(255, 255, 255));
        btn_bersih.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_bersih.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Refresh\\Refresh_24x24.png")); // NOI18N
        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });
        jPanel3.add(btn_bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Status");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Fasilitas Kamar");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txt_fasilitas.setBackground(new java.awt.Color(255, 0, 102));
        txt_fasilitas.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_fasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 180, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Add\\Add_24x24.png")); // NOI18N
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, 570));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, 600));

        jPanel5.setBackground(new java.awt.Color(255, 0, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Table Kamar"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setBackground(new java.awt.Color(255, 0, 102));
        tabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 900, 480));

        btn_cari.setBackground(new java.awt.Color(255, 255, 255));
        btn_cari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cari.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Search\\Search_16x16.png")); // NOI18N
        btn_cari.setText(" Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 80, -1));

        txt_cari.setBackground(new java.awt.Color(255, 0, 102));
        txt_cari.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });
        jPanel2.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, -1));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 920, 570));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 940, 600));

        btn_kembali.setBackground(new java.awt.Color(255, 255, 255));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_kembali.setIcon(new javax.swing.ImageIcon("D:\\knobs\\PNG\\Knob Left.png")); // NOI18N
        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        jPanel6.setBackground(new java.awt.Color(255, 0, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\home.png")); // NOI18N
        jLabel1.setText(" Data Kamar Hotel");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1340, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed

        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_txt_cariKeyPressed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int bar = tabel.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();

        txt_kmr.setText(a);
        cb_tipe.setSelectedItem(b);
        txt_tarif.setText(c);
        txt_fasilitas.setText(d);
        txt_status.setText(e);
//        atur();
    }//GEN-LAST:event_tabelMouseClicked

    private void cb_tipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipeActionPerformed
        // TODO add your handling code here:
        int harga = 0;
        if (cb_tipe.getSelectedItem() == "Standar"){
            harga = 280000;
        }
        else if(cb_tipe.getSelectedItem() == "Bisnis"){
            harga = 360000;
        }
        else if(cb_tipe.getSelectedItem() == "VIP"){
            harga = 450000;
        }
        else if(cb_tipe.getSelectedItem() == "VVIP"){
            harga = 620000;
        }
        else{
            harga = 0;
        }
        txt_tarif.setText(String.valueOf(harga));
    }//GEN-LAST:event_cb_tipeActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
       try{
            String sql = "Update tbl_kamar set Tipe_Kamar=?,Tarif=?,Fasilitas=?,Status=? where No_Kamar='"+txt_kmr.getText()+"'";
            PreparedStatement stt = con.prepareStatement(sql);
            stt.setString(1, (String) cb_tipe.getSelectedItem());
            stt.setString(2, txt_tarif.getText());
            stt.setString(3, txt_fasilitas.getText());
            stt.setString(4,txt_status.getText());
            
            stt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            txt_kmr.requestFocus();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+ e);
            }
            datatable();
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tbl_kamar values (?,?,?,?,?)";
        try{
            PreparedStatement stt = con.prepareStatement(sql);
            stt.setString(1, txt_kmr.getText());
            stt.setString(2, (String) cb_tipe.getSelectedItem());
            stt.setString(3, txt_tarif.getText());
            stt.setString(4, txt_fasilitas.getText());
            stt.setString(5, txt_status.getText());

            stt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            txt_kmr.requestFocus();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+ e);
        }
        datatable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_tarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tarifActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox cb_tipe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_fasilitas;
    private javax.swing.JTextField txt_kmr;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_tarif;
    // End of variables declaration//GEN-END:variables
}
