/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas;

import java.sql.*;//untuk mewakili semua syntax SQL
import java.awt.event.KeyEvent;//untuk mengatur posisi jform saat diruning
import javax.swing.JOptionPane;//untuk memunculkan pesan

public class Form_Menu extends javax.swing.JFrame {

    String user = "root";
    String pass = "";
    String url = "jdbc:mysql://localhost/db_hotel";//db_hotel nama databasenya
    
    public Form_Menu() {
        initComponents();
        menu_Unvisible();
        tgl.setEnabled(false);
         setLocationRelativeTo(this); //untuk mengatur posisi form
    }
    
    protected void menu_Unvisible(){
        btn_pelanggan.setEnabled(false);
        btn_kamar.setEnabled(false);
        btn_sewa.setEnabled(false);
        btn_lain.setEnabled(false);
        PanelLogin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_pelanggan = new javax.swing.JButton();
        btn_kamar = new javax.swing.JButton();
        btn_sewa = new javax.swing.JButton();
        btn_lain = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        PanelLogin = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pf_pass = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        tgl = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Login = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\User\\User_32x32.png")); // NOI18N
        jLabel1.setText("         Registry");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 209, 40));

        jPanel5.setBackground(new java.awt.Color(255, 0, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\cash (1).png")); // NOI18N
        jLabel2.setText("          Transaksi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 210, 50));

        btn_pelanggan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_pelanggan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\employees.png")); // NOI18N
        btn_pelanggan.setText(" Data Pelanggan");
        btn_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pelangganActionPerformed(evt);
            }
        });
        jPanel3.add(btn_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, 170, -1));

        btn_kamar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_kamar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\home.png")); // NOI18N
        btn_kamar.setText("   Data Kamar");
        btn_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kamarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, -1));

        btn_sewa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_sewa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\bill.png")); // NOI18N
        btn_sewa.setText(" Sewa Kamar");
        btn_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sewaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, -1));

        btn_lain.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_lain.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\hand.png")); // NOI18N
        btn_lain.setText("Transaksi Pesanan");
        btn_lain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lainActionPerformed(evt);
            }
        });
        jPanel3.add(btn_lain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 360));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 380));

        jPanel6.setBackground(new java.awt.Color(255, 0, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogin.setBackground(new java.awt.Color(255, 0, 102));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Juice ITC", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\lock.png")); // NOI18N
        jLabel4.setText("Masukan UserName dan Password Anda");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 35));

        PanelLogin.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 320, 40));

        jPanel9.setBackground(new java.awt.Color(255, 0, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Juice ITC", 1, 20)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\user.png")); // NOI18N
        jLabel3.setText(" UserName");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txt_user.setBackground(new java.awt.Color(153, 153, 153));
        txt_user.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        jPanel9.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, -1));

        jLabel5.setFont(new java.awt.Font("Juice ITC", 1, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\key.png")); // NOI18N
        jLabel5.setText(" Password");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        pf_pass.setBackground(new java.awt.Color(153, 153, 153));
        pf_pass.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        pf_pass.setForeground(new java.awt.Color(255, 255, 255));
        pf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_passActionPerformed(evt);
            }
        });
        pf_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_passKeyPressed(evt);
            }
        });
        jPanel9.add(pf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, -1));

        PanelLogin.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 320, 150));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Juice ITC", 1, 20)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\unlock.png")); // NOI18N
        login.setText(" Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel10.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, 110, 38));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Juice ITC", 1, 20)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Delete\\Delete_32x32.png")); // NOI18N
        jButton8.setText("Batal");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 11, 111, 38));

        PanelLogin.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 320, 60));

        jPanel6.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 380, 290));

        tgl.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        tgl.setModel(new javax.swing.SpinnerDateModel());
        jPanel6.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 10, 160, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 500, 380));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Login.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\login.png")); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jMenu1.add(Login);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        menu_Unvisible();
        if(Login.getText().trim().equals("Logout")){
            btn_pelanggan.setEnabled(false);
            btn_kamar.setEnabled(false);
            btn_sewa.setEnabled(false);
            btn_lain.setEnabled(false);
            Login.setText("Login");
            PanelLogin.setVisible(false);
        }else if(Login.getText().trim().equals("Login")){
            PanelLogin.setVisible(true);
            txt_user.requestFocus();
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btn_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pelangganActionPerformed
        // TODO add your handling code here:
        Form_Pelanggan Fp= new Form_Pelanggan();
        Fp.setVisible(true);
    }//GEN-LAST:event_btn_pelangganActionPerformed

    private void btn_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kamarActionPerformed
        // TODO add your handling code here:
        Form_Kamar Fk= new Form_Kamar();
        Fk.setVisible(true);
    }//GEN-LAST:event_btn_kamarActionPerformed

    private void btn_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sewaActionPerformed
        // TODO add your handling code here:
        form_sewa Fs= new form_sewa();
        Fs.setVisible(true);
    }//GEN-LAST:event_btn_sewaActionPerformed

    private void btn_lainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lainActionPerformed
        // TODO add your handling code here:
        Form_Pesanan_Lain Fpl= new Form_Pesanan_Lain();
        Fpl.setVisible(true);
    }//GEN-LAST:event_btn_lainActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try {
            Connection con= DriverManager.getConnection(url,user,pass);
            Statement stt= (Statement) con.createStatement();
            ResultSet res= stt.executeQuery("SELECT * FROM tbl_login WHERE UserName= '"+txt_user.getText()+"' AND Password='"+pf_pass.getText()+"' ");
            if (res.next()){
                if("admin".equals(res.getString("Level"))){
                    JOptionPane.showMessageDialog(null, "Anda Masuk Sebagai Admin");
                    btn_pelanggan.setEnabled(true);
                    btn_kamar.setEnabled(true);
                    btn_sewa.setEnabled(true);
                    btn_lain.setEnabled(true);
                    Login.setText("Logout");
                    PanelLogin.setVisible(false);
                    txt_user.setText("");
                    pf_pass.setText("");

                }else if("user".equals(res.getString("Level"))){
                    JOptionPane.showMessageDialog(null, "Anda Masuk Sebagai User");
                    btn_pelanggan.setEnabled(true);
                    btn_kamar.setEnabled(false);
                    btn_sewa.setEnabled(true);
                    btn_lain.setEnabled(true);
                    Login.setText("Logout");
                    PanelLogin.setVisible(false);
                    txt_user.setText("");
                    pf_pass.setText("");

                }else{

                }
            }else{
                JOptionPane.showMessageDialog(null, "UserName dan Password Salah");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_loginActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        PanelLogin.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void pf_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_passKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        }
    }//GEN-LAST:event_pf_passKeyPressed

    private void pf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_passActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Login;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JButton btn_kamar;
    private javax.swing.JButton btn_lain;
    private javax.swing.JButton btn_pelanggan;
    private javax.swing.JButton btn_sewa;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JSpinner tgl;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

}
