package tugas;

import java.io.File;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Map;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.design.JasperDesign;
import koneksi.konek;
import net.sf.jasperreports.engine.JasperPrintManager;

public class Form_Pesanan_Lain extends javax.swing.JFrame {

    int bayar;
    private Connection con= new konek().Connect();
    private DefaultTableModel tabmode;
    Object[] Baris= {"Id_Sewa","Nama","Telpon","No_Kamar","Tipe_Kamar","Tarif","Cek_in","Cek_Out","Lama_Hari","Total_Harga"};
    String Kmr, nama, tipe, tarif, lama, harga4;
    JasperReport JasRep;
    JasperPrint JasPri;
    Map param= new HashMap();
    JasperDesign JasDes;
    
    public Form_Pesanan_Lain() {
        initComponents();
        kosong();
        aktif();
        autonumber();
        atur();
        terpilihPesanan();
        hitung();
    }
    
      private void aktif(){
        txt_id.requestFocus();
    }
    
    protected void kosong(){
        txt_kmr.setText("");
        txt_nama.setText("");
        txt_harga1.setText("");
        txt_harga2.setText("");
        txt_harga3.setText("");
        cb_makanan.setSelectedItem("--Pilih Makanan--");
        cb_minuman.setSelectedItem("--Pilih Minuman--");
        cb_lain.setSelectedItem("--Pilih Pesanan--");
        txt_satuan1.setText("");
        txt_satuan2.setText("");
        txt_satuan3.setText("");
        txt_qty1.setText("");
        txt_qty2.setText("");
        txt_qty3.setText("");
        txt_total.setText("");
        txt_bayar.setText("");
        txt_total.setText("");
        txt_kembali.setText("");
        txt_tipe.setText("");
        txt_lama.setText("");
        txt_tarif.setText("");
        txt_harga4.setText("");
    }
    
     public void terpilihPesanan(){
        Form_popupPesanan Pp= new Form_popupPesanan();
        Pp.psn= this;
        txt_kmr.setText(Kmr);
        txt_nama.setText(nama);
        txt_tipe.setText(tipe);
        txt_tarif.setText(tarif);
        txt_lama.setText(lama);
        txt_harga4.setText(harga4);
    }
    
    protected void atur(){
        txt_id.setEnabled(false);
        txt_nama.setEnabled(false);
        txt_kmr.setEnabled(false);
        cb_makanan.setEnabled(true);
        cb_minuman.setEnabled(true);
        cb_lain.setEnabled(true);
        txt_satuan1.setEnabled(false);
        txt_satuan2.setEnabled(false);
        txt_satuan3.setEnabled(false);
        txt_qty1.setEnabled(true);
        txt_qty2.setEnabled(true);
        txt_qty3.setEnabled(true);
        txt_harga2.setEnabled(true);
        txt_kmr.setEnabled(false);
        txt_tipe.setEnabled(false);
        txt_tarif.setEnabled(false);
        txt_lama.setEnabled(false);
        txt_harga4.setEnabled(false);
    }
    private void autonumber(){
        String Id_Transaksi="";
        try{
            String sql= "SELECT Id_Transaksi FROM tbl_transaksi order by Id_Transaksi asc";
            PreparedStatement stt= con.prepareStatement(sql);
            ResultSet res= stt.executeQuery(sql);
            
            while(res.next()){
                Id_Transaksi= res.getString("Id_Transaksi");
            }
            }catch(SQLException sqle){Id_Transaksi="";}
        if(Id_Transaksi.length()<1){Id_Transaksi="It0000";}
        String ur= Id_Transaksi.substring(2);
        int u= Integer.parseInt(ur)+1;
        System.out.println(ur+"=="+u);
            if(u<10)
            {ur="000"+u;}
            else if(u<100)
            {ur="00"+u;}
            else if(u<1000)
            {ur="0"+u;}
            else
            {ur=""+u;}
        Id_Transaksi= "It"+ur;
        txt_id.setText(Id_Transaksi);   
    }
    
     private void hitung(){
        DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
        int jumlah= dataModel.getRowCount();
        int Harga= 0;
        
        for(int i=0; i<tabel.getRowCount(); i++){
            int amount= Integer.valueOf(tabel.getValueAt(i, 6).toString());
            Harga+= amount;                  
        }
        txt_total.setText(Double.toString(Harga));
        txt_jumlah.setText(Integer.toString(jumlah));
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_cari = new javax.swing.JButton();
        txt_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_qty2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_qty1 = new javax.swing.JTextField();
        txt_satuan2 = new javax.swing.JTextField();
        cb_makanan = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txt_kmr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_satuan1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_minuman = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_lain = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_satuan3 = new javax.swing.JTextField();
        txt_qty3 = new javax.swing.JTextField();
        tambah1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txt_harga2 = new javax.swing.JTextField();
        txt_harga1 = new javax.swing.JTextField();
        tambah3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_harga3 = new javax.swing.JTextField();
        tambah2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_tarif = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_lama = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_harga4 = new javax.swing.JTextField();
        tambah4 = new javax.swing.JButton();
        txt_tipe = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_jumlah = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_kembali = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tgl = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ary Afrilliand\\Downloads\\hand.png")); // NOI18N
        jLabel1.setText(" Transaksi Pesanan");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1340, 50));

        btn_kembali.setBackground(new java.awt.Color(255, 255, 255));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_kembali.setIcon(new javax.swing.ImageIcon("D:\\knobs\\PNG\\Knob Left.png")); // NOI18N
        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        jPanel6.setBackground(new java.awt.Color(255, 0, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cari.setBackground(new java.awt.Color(255, 255, 255));
        btn_cari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cari.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Search\\Search_16x16.png")); // NOI18N
        btn_cari.setText(" Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        txt_nama.setBackground(new java.awt.Color(255, 0, 102));
        txt_nama.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Nama");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Makanan");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Minuman");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        txt_qty2.setBackground(new java.awt.Color(255, 0, 102));
        txt_qty2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qty2ActionPerformed(evt);
            }
        });
        txt_qty2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qty2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_qty2KeyTyped(evt);
            }
        });
        jPanel3.add(txt_qty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 60, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Qty");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        txt_qty1.setBackground(new java.awt.Color(255, 0, 102));
        txt_qty1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qty1ActionPerformed(evt);
            }
        });
        txt_qty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qty1KeyReleased(evt);
            }
        });
        jPanel3.add(txt_qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 60, -1));

        txt_satuan2.setBackground(new java.awt.Color(255, 0, 102));
        txt_satuan2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_satuan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 150, -1));

        cb_makanan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cb_makanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Makanan--", "Nasi Putih", "Nasi Goreng", "Mie Goreng", "Nasi + Ayam Bakar", "Nasi + Ayam Goreng", "Nasi + Ayam Crispy", "Nasi + Ikan Bakar", "Nasi + Ikan Goreng", "Nasi + Ikan Asam Manis", "Udang Saus Tiram", "Udang Bakar", "Kepiting Saus Tiram", "Kerang Balado", "Fuyunghai", "Kentang Goreng", "Otak - Otak Goreng", "Baso Goreng", "Baso Kuah", "Baso Tahu" }));
        cb_makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_makananActionPerformed(evt);
            }
        });
        jPanel3.add(cb_makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 130, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("No. Kamar");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txt_kmr.setBackground(new java.awt.Color(255, 0, 102));
        txt_kmr.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_kmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Satuan Harga");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        txt_satuan1.setBackground(new java.awt.Color(255, 0, 102));
        txt_satuan1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_satuan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 130, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Qty");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        cb_minuman.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cb_minuman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Minuman--", "Air Putih", "Teh Manis (Dingin / Panas)", "Teh Tawar (Dingin / Panas)", "Air Jeruk (Dingin / Panas)", "Coffe Black (Dingin / Panas)", "Coffe Susu (Dingin / Panas)", "Cappucino (Dingin / Panas)", "Vanilla Latte (Dingin / Panas)", "Milo (Dingin / Panas)", "Jus Buah" }));
        cb_minuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_minumanActionPerformed(evt);
            }
        });
        jPanel3.add(cb_minuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 150, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Satuan Harga");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Pesanan Lain");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1041, 24, -1, -1));

        cb_lain.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cb_lain.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Pesanan--", "Meeting Room", "Pijat / Spa", "Karaoke", "Fitness" }));
        cb_lain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_lainActionPerformed(evt);
            }
        });
        jPanel3.add(cb_lain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 150, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Satuan Harga");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Qty / Lama Jam");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, -1, -1));

        txt_satuan3.setBackground(new java.awt.Color(255, 0, 102));
        txt_satuan3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_satuan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 147, -1));

        txt_qty3.setBackground(new java.awt.Color(255, 0, 102));
        txt_qty3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_qty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qty3ActionPerformed(evt);
            }
        });
        txt_qty3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qty3KeyReleased(evt);
            }
        });
        jPanel3.add(txt_qty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 61, -1));

        tambah1.setBackground(new java.awt.Color(255, 255, 255));
        tambah1.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Add\\Add_16x16.png")); // NOI18N
        tambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah1MouseClicked(evt);
            }
        });
        tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah1ActionPerformed(evt);
            }
        });
        jPanel3.add(tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 40, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Harga");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        txt_harga2.setBackground(new java.awt.Color(255, 0, 102));
        txt_harga2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jPanel3.add(txt_harga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 120, 30));

        txt_harga1.setBackground(new java.awt.Color(255, 0, 102));
        txt_harga1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jPanel3.add(txt_harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 90, 30));

        tambah3.setBackground(new java.awt.Color(255, 255, 255));
        tambah3.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Add\\Add_16x16.png")); // NOI18N
        tambah3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah3MouseClicked(evt);
            }
        });
        tambah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah3ActionPerformed(evt);
            }
        });
        jPanel3.add(tambah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 110, 40, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("Harga");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("Harga");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        txt_harga3.setBackground(new java.awt.Color(255, 0, 102));
        txt_harga3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txt_harga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_harga3ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_harga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, 120, 30));

        tambah2.setBackground(new java.awt.Color(255, 255, 255));
        tambah2.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Add\\Add_16x16.png")); // NOI18N
        tambah2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah2MouseClicked(evt);
            }
        });
        tambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah2ActionPerformed(evt);
            }
        });
        jPanel3.add(tambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Id Transaksi");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txt_id.setBackground(new java.awt.Color(255, 0, 102));
        txt_id.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("Tipe Kamar");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText("Tarif");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        txt_tarif.setBackground(new java.awt.Color(255, 0, 102));
        txt_tarif.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 110, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setText("Lama Menginap");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        txt_lama.setBackground(new java.awt.Color(255, 0, 102));
        txt_lama.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 60, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel24.setText("Harga");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        txt_harga4.setBackground(new java.awt.Color(255, 0, 102));
        txt_harga4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_harga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 80, 30));

        tambah4.setBackground(new java.awt.Color(255, 255, 255));
        tambah4.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Add\\Add_16x16.png")); // NOI18N
        tambah4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah4MouseClicked(evt);
            }
        });
        tambah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah4ActionPerformed(evt);
            }
        });
        jPanel3.add(tambah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 40, 30));

        txt_tipe.setBackground(new java.awt.Color(255, 0, 102));
        txt_tipe.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(txt_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1320, 150));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1340, 170));

        jPanel7.setBackground(new java.awt.Color(255, 0, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setBackground(new java.awt.Color(255, 0, 102));
        tabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Transaksi", "No. Kamar", "Nama", "Pesanan", "Satuan Harga", "Qty", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1300, 110));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Refresh\\Refresh_16x16.png")); // NOI18N
        jButton1.setText("Batal");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 130, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Remove\\Remove_16x16.png")); // NOI18N
        jButton4.setText("Hapus");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, -1, -1));

        txt_jumlah.setBackground(new java.awt.Color(255, 0, 102));
        txt_jumlah.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel4.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 60, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("Jumlah Pesanan");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 1316, 169));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1340, 200));

        jPanel8.setBackground(new java.awt.Color(255, 0, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Total Harga");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Bayar");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Kembali");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        txt_total.setBackground(new java.awt.Color(255, 0, 102));
        txt_total.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel5.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 13, 310, 61));

        txt_bayar.setBackground(new java.awt.Color(255, 0, 102));
        txt_bayar.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
        });
        jPanel5.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 93, 310, 28));

        txt_kembali.setBackground(new java.awt.Color(255, 0, 102));
        txt_kembali.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel5.add(txt_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 139, 310, 28));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Print\\Print_16x16.png")); // NOI18N
        jButton2.setText(" Cetak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("D:\\must_have_icon_set\\Undo\\Undo_16x16.png")); // NOI18N
        jButton3.setText(" Bersih");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jButton5.setText("Cetak");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 220));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 470, 240));

        tgl.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        tgl.setModel(new javax.swing.SpinnerDateModel());
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qty2ActionPerformed
        // TODO add your handling code here:
        int beli, harga, ttl;
        beli= Integer.parseInt(txt_satuan2.getText());
        harga= Integer.parseInt(txt_qty2.getText());
        ttl= beli*harga;
        txt_harga2.setText(String.valueOf(ttl)); 
    }//GEN-LAST:event_txt_qty2ActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        Form_popupPesanan Pp= new Form_popupPesanan();
        Pp.psn= this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void cb_makananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_makananActionPerformed
        // TODO add your handling code here:
        int harga = 0;
        if (cb_makanan.getSelectedItem() == "Nasi Putih"){
            harga = 5000;
        }
        else if(cb_makanan.getSelectedItem() == "Nasi Goreng"){
            harga = 30000;
        }
        else if(cb_makanan.getSelectedItem() == "Mie Goreng"){
            harga = 30000;
        }
        else if(cb_makanan.getSelectedItem() == "Nasi + Ayam Bakar"){
            harga = 30000;
        }  
        else if(cb_makanan.getSelectedItem() == "Nasi + Ayam Goreng"){
            harga = 30000;
        }  
        else if(cb_makanan.getSelectedItem() == "Nasi + Ayam Crispy"){
            harga = 30000;
        }  
        else if(cb_makanan.getSelectedItem() == "Nasi + Ikan Bakar"){
            harga = 35000;
        }  
        else if(cb_makanan.getSelectedItem() == "Nasi + Ikan Goreng"){
            harga = 35000;
        }
        else if(cb_makanan.getSelectedItem() == "Nasi + Ikan Asam Manis"){
            harga = 35000;
        }
        else if(cb_makanan.getSelectedItem() == "Udang Saus Tiram"){
            harga = 45000;
        }
        else if(cb_makanan.getSelectedItem() == "Udang Bakar"){
            harga = 45000;
        }
        else if(cb_makanan.getSelectedItem() == "Kepiting Saus Tiram"){
            harga = 45000;
        }
        else if(cb_makanan.getSelectedItem() == "Kerang Balado"){
            harga = 25000;
        }
        else if(cb_makanan.getSelectedItem() == "Fuyunghai"){
            harga = 45000;
        }
        else if(cb_makanan.getSelectedItem() == "Kentang Goreng"){
            harga = 10000;
        }
        else if(cb_makanan.getSelectedItem() == "Otak - Otak Goreng"){
            harga = 15000;
        }
        else if(cb_makanan.getSelectedItem() == "Baso Goreng"){
            harga = 15000;
        }
        else if(cb_makanan.getSelectedItem() == "Baso Kuah"){
            harga = 20000;
        }
        else if(cb_makanan.getSelectedItem() == "Baso Tahu"){
            harga = 20000;
        }
        else{
            harga = 0;
        }
        txt_satuan1.setText(String.valueOf(harga));                                    
    }//GEN-LAST:event_cb_makananActionPerformed

    private void txt_qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qty1ActionPerformed
        // TODO add your handling code here:
        int beli, harga, ttl;
        beli= Integer.parseInt(txt_satuan1.getText());
        harga= Integer.parseInt(txt_qty1.getText());
        ttl= beli*harga;
        txt_harga2.setText(String.valueOf(ttl)); 
    }//GEN-LAST:event_txt_qty1ActionPerformed

    private void txt_qty1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qty1KeyReleased
        // TODO add your handling code here:
        int x, y, z;
        x= Integer.valueOf(txt_satuan1.getText());
        y= Integer.valueOf(txt_qty1.getText());
        z= x*y;
        txt_harga1.setText("" +z);
    }//GEN-LAST:event_txt_qty1KeyReleased

    private void cb_minumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_minumanActionPerformed
        // TODO add your handling code here:
        int harga = 0;
        if (cb_minuman.getSelectedItem() == "Air Putih"){
            harga = 0;
        }
        else if(cb_minuman.getSelectedItem() == "Teh Manis (Dingin / Panas)"){
            harga = 5000;
        }
        else if(cb_minuman.getSelectedItem() == "Teh Tawar (Dingin / Panas)"){
            harga = 5000;
        }
         else if(cb_minuman.getSelectedItem() == "Air Jeruk (Dingin / Panas)"){
            harga = 10000;
        }
        else if(cb_minuman.getSelectedItem() == "Coffe Black (Dingin / Panas)"){
            harga = 12000;
        }
         else if(cb_minuman.getSelectedItem() == "Coffe Susu (Dingin / Panas)"){
            harga = 15000;
        }
        else if(cb_minuman.getSelectedItem() == "Cappucino (Dingin / Panas)"){
            harga = 15000;
        }
         else if(cb_minuman.getSelectedItem() == "Vanilla Latte (Dingin / Panas)"){
            harga = 15000;
        }
        else if(cb_minuman.getSelectedItem() == "Milo (Dingin / Panas)"){
            harga = 15000;
        }
        else if(cb_minuman.getSelectedItem() == "Jus Buah"){
            harga = 25000;
        }
        else{
            harga = 0;
        }
        txt_satuan2.setText(String.valueOf(harga));
    }//GEN-LAST:event_cb_minumanActionPerformed

    private void txt_qty2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qty2KeyReleased
        // TODO add your handling code here:
        int x, y, z;
        x= Integer.valueOf(txt_satuan2.getText());
        y= Integer.valueOf(txt_qty2.getText());
        z= x*y;
        txt_harga2.setText("" +z);
    }//GEN-LAST:event_txt_qty2KeyReleased

    private void cb_lainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_lainActionPerformed
        // TODO add your handling code here:
        int harga= 0;
        if(cb_lain.getSelectedItem() == "Meeting Room"){
            harga = 200000;
        }
        else if(cb_lain.getSelectedItem() == "Pijat / Spa"){
            harga = 150000;
        }
        else if(cb_lain.getSelectedItem() == "Karaoke"){
            harga = 175000;
        }
        else if(cb_lain.getSelectedItem() == "Fitness"){
            harga = 75000;
        }
        else{
            harga = 0;
        }
        txt_satuan3.setText(String.valueOf(harga));
    }//GEN-LAST:event_cb_lainActionPerformed

    private void txt_qty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qty3ActionPerformed
        // TODO add your handling code here:
        int tarif, lama, harga;
        tarif= Integer.parseInt(txt_satuan3.getText());
        lama= Integer.parseInt(txt_qty3.getText());
        harga= tarif*lama;
        txt_harga2.setText(String.valueOf(harga));
    }//GEN-LAST:event_txt_qty3ActionPerformed

    private void txt_qty3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qty3KeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a= Integer.valueOf(txt_satuan3.getText());
        b= Integer.valueOf(txt_qty3.getText());
        c= a*b;
        txt_harga3.setText("" +c);
    }//GEN-LAST:event_txt_qty3KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah1ActionPerformed

    private void tambah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
        List list= new ArrayList<>();
        list.add(txt_id.getText());
        list.add(txt_kmr.getText());
        list.add(txt_nama.getText());
        list.add(cb_makanan.getSelectedItem());
        list.add(txt_satuan1.getText());
        list.add(txt_qty1.getText());
        list.add(txt_harga1.getText());
        dataModel.addRow(list.toArray());
        hitung();
    }//GEN-LAST:event_tambah1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void tambah3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
        List list= new ArrayList<>();
        list.add(txt_id.getText());
        list.add(txt_kmr.getText());
        list.add(txt_nama.getText());
        list.add(cb_lain.getSelectedItem());
        list.add(txt_satuan3.getText());
        list.add(txt_qty3.getText());
        list.add(txt_harga3.getText());
        dataModel.addRow(list.toArray());
        hitung();
    }//GEN-LAST:event_tambah3MouseClicked

    private void tambah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah3ActionPerformed

    private void tambah2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
        List list= new ArrayList<>();
        list.add(txt_id.getText());
        list.add(txt_kmr.getText());
        list.add(txt_nama.getText());
        list.add(cb_minuman.getSelectedItem());
        list.add(txt_satuan2.getText());
        list.add(txt_qty2.getText());
        list.add(txt_harga2.getText());
        dataModel.addRow(list.toArray());
        hitung();
    }//GEN-LAST:event_tambah2MouseClicked

    private void tambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah2ActionPerformed

    private void txt_qty2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qty2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qty2KeyTyped

    private void txt_harga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_harga3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_harga3ActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
        double duit, total, kembali;
        duit= Double.parseDouble(txt_bayar.getText());
        total= Double.parseDouble(txt_total.getText());
        kembali= duit - total;
        String xkem= Double.toString(kembali);
        txt_kembali.setText(xkem);
      
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarKeyReleased

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int index= tabel.getSelectedRow();
         DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
         dataModel.removeRow(index);
         tabel.setModel(dataModel);
         hitung();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
        if (tabel.getRowCount()>0){
            for(int i= tabel.getRowCount()-1; i>-1; i--){
                dataModel.removeRow(i);

                txt_kmr.setText("");
                txt_nama.setText("");
                cb_makanan.setSelectedItem("--Pilih Makanan--");
                txt_satuan1.setText("");
                txt_qty1.setText("");
                txt_harga2.setText("");
                txt_jumlah.setText("");
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed

        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void tambah4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
        List list= new ArrayList<>();
        list.add(txt_id.getText());
        list.add(txt_kmr.getText());
        list.add(txt_nama.getText());
        list.add(txt_tipe.getText());
        list.add(txt_tarif.getText());
        list.add(txt_lama.getText());
        list.add(txt_harga4.getText());
        dataModel.addRow(list.toArray());
        hitung();
    }//GEN-LAST:event_tambah4MouseClicked

    private void tambah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String fd= sdf.format(tgl.getValue());
        String sql= "insert into tbl_transaksi values (?,?,?,?,?,?,?)";
        String zsql= "insert into tbl_isi values(?,?,?,?,?)" ;
        try{
            
            PreparedStatement stt= con.prepareStatement(sql);
            stt.setString(1, txt_id.getText());
            stt.setString(2, fd);
            stt.setString(3, txt_kmr.getText());
            stt.setString(4, txt_nama.getText());
            stt.setString(5, txt_total.getText());
            stt.setString(6, txt_bayar.getText());
            stt.setString(7, txt_kembali.getText());
            
            stt.executeUpdate();
            
            int t= tabel.getRowCount();
            for(int i= 0; i<t; i++){
                
            String pesanan= tabel.getValueAt(i, 3).toString();
            String Satuan= tabel.getValueAt(i, 4).toString();
            String Qty= tabel.getValueAt(i, 5).toString();
            String Harga= tabel.getValueAt(i, 6).toString();
            
            PreparedStatement stt2= con.prepareStatement(zsql);
            stt2.setString(1,txt_id.getText());
            stt2.setString(2, pesanan );
            stt2.setString(3, Satuan );
            stt2.setString(4, Qty );
            stt2.setString(5, Harga );
            
            stt2.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Selesai");
        }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" +e);
                    }   
                    aktif();
                    autonumber();
                    kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       /* try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection con= DriverManager.getConnection("jdbc:mysql://localhost/db_hotel","root","");
          Statement stat= con.createStatement();
          
          try{
              File reprt= new File("src/Laporan/report2.jrxml");
              JasDes= JRXmlLoader.load(reprt);
              Integer p= Integer.parseInt(txt_kmr.getText());
              param.clear();
              param.put("nkm", p);
              JasRep= JasperCompileManager.compileReport(JasDes);
              JasPri= JasperFillManager.fillReport(JasRep, param, con);
              JasperViewer.viewReport(JasPri,false);
              JasperPrintManager.printReport(JasPri, true);
          }catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
          }
              
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Kesalahan");
          }*/
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            HashMap data= new HashMap();
        String sql= "SELECT Id_Transaksi"
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pesanan_Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pesanan_Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pesanan_Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pesanan_Lain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Pesanan_Lain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JComboBox cb_lain;
    private javax.swing.JComboBox cb_makanan;
    private javax.swing.JComboBox cb_minuman;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah1;
    private javax.swing.JButton tambah2;
    private javax.swing.JButton tambah3;
    private javax.swing.JButton tambah4;
    private javax.swing.JSpinner tgl;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga1;
    private javax.swing.JTextField txt_harga2;
    private javax.swing.JTextField txt_harga3;
    private javax.swing.JTextField txt_harga4;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_kmr;
    private javax.swing.JTextField txt_lama;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_qty1;
    private javax.swing.JTextField txt_qty2;
    private javax.swing.JTextField txt_qty3;
    private javax.swing.JTextField txt_satuan1;
    private javax.swing.JTextField txt_satuan2;
    private javax.swing.JTextField txt_satuan3;
    private javax.swing.JTextField txt_tarif;
    private javax.swing.JTextField txt_tipe;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
